# Google Cloud Build configuration for VisionStock
# This file is used for automated builds and deployments to Cloud Run

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/visionstock-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/visionstock-backend:latest'
      - '-f'
      - 'backend/Dockerfile'
      - '.'

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/visionstock-backend:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/visionstock-backend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'visionstock-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/visionstock-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'PYTHONPATH=/app,PYTHONUNBUFFERED=1'

images:
  - 'gcr.io/$PROJECT_ID/visionstock-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/visionstock-backend:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'

